server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.xml            # mybatis配置文件所在路径
  type-aliases-package: com.sqp.springcloud.entities        # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
      name: microservicecloud-dept
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://45.40.204.40:3306/test?useUnicode=true&characterEncoding=UTF-8           # 数据库名称
      username: root
      password: 123456
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
logging: 
    level:
      com:
        sqp:
          springcloud:
            dao: debug
debug: true